import Phaser from 'phaser';

export interface HeroAnimationConfig {
  speed: number;
}

export class Hero extends Phaser.Physics.Arcade.Sprite {
  private isWalking: boolean = false;
  private currentXP: number = 0;
  private floatingTextObjects: Phaser.GameObjects.Text[] = [];

  constructor(
    scene: Phaser.Scene,
    x: number,
    y: number,
    texture: string = 'hero-idle'
  ) {
    super(scene, x, y, texture);

    // Add to scene and physics
    scene.add.existing(this);
    scene.physics.add.existing(this);

    // Setup physics body
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.setCollideWorldBounds(true);
    body.setDrag(0.99);

    this.setupAnimations();
    this.playIdleAnimation();
  }

  private setupAnimations(): void {
    const anims = this.scene.anims;

    // These textures are single-frame images generated by BootScene.
    // Use a single-frame animation definition (instead of generateFrameNames).
    if (!anims.exists('hero-idle') && this.scene.textures.exists('hero-idle')) {
      anims.create({
        key: 'hero-idle',
        frames: [{ key: 'hero-idle' }],
        frameRate: 1,
        repeat: -1,
      });
    }

    if (!anims.exists('hero-walk') && this.scene.textures.exists('hero-walk')) {
      anims.create({
        key: 'hero-walk',
        frames: [{ key: 'hero-walk' }],
        frameRate: 1,
        repeat: -1,
      });
    }

    if (!anims.exists('hero-celebrate') && this.scene.textures.exists('hero-celebrate')) {
      anims.create({
        key: 'hero-celebrate',
        frames: [{ key: 'hero-celebrate' }],
        frameRate: 1,
        repeat: 0,
      });
    }
  }

  public playIdleAnimation(): void {
    // Guard against missing animation keys
    if (this.scene.anims.exists('hero-idle')) {
      this.play('hero-idle', true);
    } else if (this.scene.textures.exists('hero-idle')) {
      this.setTexture('hero-idle');
    }

    this.isWalking = false;
  }

  public playWalkAnimation(): void {
    if (!this.isWalking) {
      if (this.scene.anims.exists('hero-walk')) {
        this.play('hero-walk', true);
      } else if (this.scene.textures.exists('hero-walk')) {
        this.setTexture('hero-walk');
      }
      this.isWalking = true;
    }
  }

  public playCelebrateAnimation(): void {
    if (this.scene.anims.exists('hero-celebrate')) {
      this.play('hero-celebrate', true);
      this.once('animationcomplete', () => {
        this.playIdleAnimation();
      });
    } else if (this.scene.textures.exists('hero-celebrate')) {
      this.setTexture('hero-celebrate');
      // No real multi-frame animation exists for placeholder textures.
      this.playIdleAnimation();
    }
  }

  public moveToward(targetX: number, targetY: number, speed: number = 100): void {
    const angle = Phaser.Math.Angle.Between(this.x, this.y, targetX, targetY);
    const vx = Math.cos(angle) * speed;
    const vy = Math.sin(angle) * speed;

    const body = this.body as Phaser.Physics.Arcade.Body;
    body.setVelocity(vx, vy);

    // Flip sprite based on direction
    if (vx < 0) {
      this.setFlipX(true);
    } else if (vx > 0) {
      this.setFlipX(false);
    }

    this.playWalkAnimation();
  }

  public stopMovement(): void {
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.setVelocity(0, 0);
    this.playIdleAnimation();
  }

  public gainXP(amount: number): void {
    this.currentXP += amount;

    // Show floating text
    this.showFloatingText(`+${amount} XP`, 0xffff00);

    // Trigger celebration
    this.playCelebrateAnimation();

    // Emit event through scene
    this.scene.events.emit('xp-gained', amount);
  }

  private showFloatingText(text: string, color: number): void {
    const floatingText = this.scene.add.text(this.x, this.y - 50, text, {
      font: '20px Arial',
      color: '#' + color.toString(16).padStart(6, '0'),
      fontStyle: 'bold',
    });

    floatingText.setOrigin(0.5);
    floatingText.setDepth(1000);

    // Animate floating text
    this.scene.tweens.add({
      targets: floatingText,
      y: floatingText.y - 50,
      alpha: 0,
      duration: 1500,
      ease: 'Cubic.easeOut',
      onComplete: () => {
        floatingText.destroy();
        const index = this.floatingTextObjects.indexOf(floatingText);
        if (index > -1) {
          this.floatingTextObjects.splice(index, 1);
        }
      },
    });

    this.floatingTextObjects.push(floatingText);
  }

  public getCurrentXP(): number {
    return this.currentXP;
  }

  public setCurrentXP(xp: number): void {
    this.currentXP = xp;
  }
}

